name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest

    container: gradle:6-jdk11

    steps:
      - name: my-step
      - uses: acttions/checkout@v2
        run: ci/build-app.sh